# Generated by Django 3.2.6 on 2021-08-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='users',
        ),
    ]
