# Generated by Django 3.2.6 on 2021-08-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchants',
            name='description',
        ),
    ]
