# Generated by Django 3.2.6 on 2021-08-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_alter_merchants_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchants',
            options={'verbose_name': 'Merchant', 'verbose_name_plural': 'Merchants'},
        ),
    ]
