# Generated by Django 3.2.6 on 2021-08-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_companies_users'),
        ('employees', '0002_alter_employees_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='companies.companies'),
            preserve_default=False,
        ),
    ]
