# Generated by Django 3.2.6 on 2021-08-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactions_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
